version: "3"
services:
    relay:
        build: .
        ports:
            - 5050:5000
    tts:
        env_file: test.env
        build: ../cloud-computing
        ports:
            - 5000:5000
    